#:schema node_modules/wrangler/config-schema.json
name = "dawn-queen-9eaf"
main = "src/index.js"
compatibility_date = "2024-08-21"
kv_namespaces = [
  { binding = "MY_KV", id = "" }
]
node_compat = true
nodejs_compat = true
workers_dev = true